### ISSUE TITLE
How do I include custom header files?

### ISSUE THREAD

**Issue by SolarSunrise** [lvzixun/clang-complete#3]
Thanks for the awesome plugin! One question however, how do I include custom header files through my project settings (*.sublime-project)? If that works, then this program is pretty much one of the best C autocomplete plugin out there.

Thanks!

**Comment by lvzixun** [comment]
update plugin to 0.1.1. support sublime project setting.
add somthing like the following to the `settings` section in your `<name>.sublime-project` file:

```
"settings":
{
    "cc_include_options":
    [
        "-I/headfile_path1",
        "-I/headfile_path2",
        "-I/headfile_path3",
        ...
    ]
    ...
}
```

if `"cc_include_options"` exists in your project settings, it'll override rather than add
to the`"include_options"` defined in cc.sublime-settings. ;)

**Comment by SolarSunrise** [comment]
Thanks for the update! I'll try it out and report bugs if there are any.
